# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: SneakyPackets
google_analytics: SneakyPackets
title: SneakyPackets

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: SneakyPackets

description: Tech blog
author:
  name: SneakyPackets
  email: hello@sneakypackets.com
  github: SneakyPackets
  twitter: SneakyPackets
  bio: 
  email_md5: 2cbfc554c6488bf0d6aa74d4efdae248


rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
